phrase:
  access_token: 47489af89b3b5c0ba8a18df4196ecc1b039d5d15e73aae847eae7e46ebf14a30
  project_id: dca660bf649a06739d040ffce94c94d3
  file_format: laravel
  push:
    sources:

    # Spanish
    - file: ./api/lang/es/*.php
      params:
        locale_id: es
        tags: "Main files"
    - file: ./api/lang/es/emails/bookings/*.php
      params:
        locale_id: es
        tags: "Emails"
    - file: ./api/lang/es/excursions/*.php
      params:
        locale_id: es
        tags: "Excursions"
    - file: ./api/lang/es/extras/*.php
      params:
        locale_id: es
        tags: "Extras"
    - file: ./api/lang/es/pdfs/*.php
      params:
        locale_id: es
        tags: "PDFs"

    - file: ./web/lang/es/*.php
      params:
        locale_id: es
        tags: "Main files"
    - file: ./web/lang/es/destinations/*.php
      params:
        locale_id: es
        tags: "Destinations"
    - file: ./web/lang/es/errors/*.php
      params:
        locale_id: es
        tags: "Errors"
    - file: ./web/lang/es/includes/*.php
      params:
        locale_id: es
        tags: "Includes"
    - file: ./web/lang/es/schedules/*.php
      params:
        locale_id: es
        tags: "Schedules"

  pull:
    targets:

    # German
    - file: ./api/lang/fr/activities.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./api/lang/fr/mains.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./api/lang/fr/services.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./api/lang/fr/emails/bookings/cancellation.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Emails"
    - file: ./api/lang/fr/emails/bookings/confirmation.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Emails"
    - file: ./api/lang/fr/excursions/EDN.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/ENFU.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/FEXB.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/GAT.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/GT.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/ILG.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/ILOSU.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/ILP.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/LEXB.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/LOAIR.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/LOBYN.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/LOBYRN.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/LWT2N.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/LWT2R.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/MEGR.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/excursions/VOL.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Excursions"
    - file: ./api/lang/fr/extras/transfer.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Extras"
    - file: ./api/lang/fr/pdfs/ticket.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "PDFs"
    - file: ./web/lang/fr/blog.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/conditions.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/contact.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/cookies.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/excursion.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/excursions.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/gateway.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/journey.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/legal-warning.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/main.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/maintenance.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/policy.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/rates.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/response.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/schedule.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/ticket.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/transfers.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/waterbus.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Main_files"
    - file: ./web/lang/fr/destinations/fuerteventura.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
    - file: ./web/lang/fr/destinations/lanzarote.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
    - file: ./web/lang/fr/destinations/lagraciosa.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
    - file: ./web/lang/fr/destinations/main.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
    - file: ./web/lang/fr/errors/404.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Errors"
    - file: ./web/lang/fr/errors/504.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Errors"
    - file: ./web/lang/fr/includes/floating-menu.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Includes"
    - file: ./web/lang/fr/includes/footer.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Includes"
    - file: ./web/lang/fr/includes/language.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Includes"
    - file: ./web/lang/fr/includes/messages.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Includes"
    - file: ./web/lang/fr/includes/navbar.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Includes"
    - file: ./web/lang/fr/schedules/lnz-ftv.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Schedules"
    - file: ./web/lang/fr/schedules/lnz-lg.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Schedules"
    - file: ./web/lang/fr/schedules/main.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Schedules"
